lines = [
    "import streamlit as st",
    "from langchain_huggingface import HuggingFaceEmbeddings",
    "from langchain_chroma import Chroma",
    "from langchain_groq import ChatGroq",
    "from langchain_core.prompts import ChatPromptTemplate",
    "from langchain_core.messages import HumanMessage, AIMessage",
    "from langchain_core.output_parsers import StrOutputParser",
    "from langchain_community.document_loaders import PyPDFLoader",
    "from langchain_text_splitters import RecursiveCharacterTextSplitter",
    "from dotenv import load_dotenv",
    "import os",
    "import tempfile",
    "",
    "load_dotenv()",
    "",
    "st.set_page_config(page_title='RAG Chatbot', page_icon='🤖', layout='centered')",
    "st.title('🤖 RAG Chatbot')",
    "st.caption('Upload PDFs and ask me anything!')",
    "",
    "@st.cache_resource",
    "def load_models():",
    "    embeddings = HuggingFaceEmbeddings(model_name='BAAI/bge-small-en-v1.5')",
    "    llm = ChatGroq(api_key=os.getenv('GROQ_API_KEY'), model='llama-3.1-8b-instant')",
    "    return embeddings, llm",
    "",
    "embeddings, llm = load_models()",
    "",
    "if 'messages' not in st.session_state:",
    "    st.session_state.messages = []",
    "if 'chat_history' not in st.session_state:",
    "    st.session_state.chat_history = []",
    "if 'uploaded_files' not in st.session_state:",
    "    st.session_state.uploaded_files = []",
    "",
    "with st.sidebar:",
    "    st.header('📄 Upload Documents')",
    "    uploaded_files = st.file_uploader('Upload PDF files', type=['pdf'], accept_multiple_files=True)",
    "    if uploaded_files:",
    "        new_files = [f.name for f in uploaded_files if f.name not in st.session_state.uploaded_files]",
    "        if new_files:",
    "            with st.spinner('Processing PDFs...'):",
    "                all_chunks = []",